<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10"/>
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
      <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
      <PackageReference Include="Scalar.AspNetCore" Version="2.16.15" />
      <PackageReference Include="FastEndpoints" Version="8.1.0" />
      <PackageReference Include="FastEndpoints.Swagger" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Neshin.Application\Neshin.Application.csproj" />
    <ProjectReference Include="..\Neshin.Infrastructure\Neshin.Infrastructure.csproj" />
  </ItemGroup>

</Project>
